### ISSUE TITLE
Account keeps getting deactivated

### ISSUE THREAD

**Issue by SPChrisW** [Picovoice/pico-cookbook#17]
I am a developer from Hong Kong, and my accounts keep getting deactivated, though I did nothing. May I ask if it is because of the region I am in?

**Comment by ErisMik** [comment]
Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.

If you think there is a mistake, you can let us know by filling out [this form](https://forms.gle/m2TQwUUavDvFKhGS7).
