### ISSUE TITLE
Android: Runtime error with llm-voice-assistant: Cannot invoke "String.lenght()" because "" is null

### ISSUE THREAD

**Issue by itzjac** [Picovoice/pico-cookbook#29]
Hello,

I just cloned the pico-cookbook and loaded the project into Android Studio. 

After applying my personal access key from your website, the app can be launched but it crashes with 

`
Cannot invoke "String.lenght()" because "" is null
`

Project settings are JDK 21, Gradle 8.9.

I am totally new into it, disregard this as a bug report but appreciate any of your help.

**Comment by albho** [comment]
Can you share where in the code that error gets thrown?

**Comment by itzjac** [comment]
Hi,

I got pass that error. Sorry, i can't detail what was the solution as I tried different combinations of gradle and JDK. Is there any other channel I can connect for more support?

**Comment by albho** [comment]
Glad you got past it! GitHub Issues is the ideal channel for support. If you need more dedicated support as a free plan user, we offer the [Enterprise Support Add-on](https://picovoice.ai/professional-services/).
