### ISSUE TITLE
picoLLM model giving an error?

### ISSUE THREAD

**Issue by andrewatliferay** [Picovoice/pico-cookbook#7]
Perhaps I am doing something wrong but I can't get the Web demo to work. 

I cloned the repo and ran all the yarn commands. Once done I am able to go to localhost:500 and see the app runinng. I entered my console key and then selected a model. I've tried two different models so far, but haven't had any luck.

1. llama-3-8b-318.pllm
2. llama-3-8b-instruct-326.pllm

.. in both cases the initialization fails with the same error message. 

Error: Initialization failed: 
  [0] picoLLM model `.pllm` file belongs to a different version of the library. File is `1.0.0` while library is `0.1.X`.
  [1] Picovoice Error (code `00000136`)

-- can you tell me what I might be doing wrong? I only see v1 model options for download when I go to https://console.picovoice.ai/picollm

**Comment by ErisMik** [comment]
Hi @andrewatliferay thank you for the report. The picollm package version in the `package.json` and `yarn.lock` was out of date. I have updated the example in this repo to the latest. Please pull the latest version, try again and let me know if that resolves your issue. Additionally you can just run `yarn upgrade` which will accomplish the same thing.

**Comment by andrewatliferay** [comment]
Awesome -- worked like a charm. Thank you!
