### ISSUE TITLE
Speech not always converting to text for outlier words

### ISSUE THREAD

**Issue by andrewatliferay** [Picovoice/pico-cookbook#9]
Hey Guys --

I'm not sure that this is an "issue" exactly but I thought I would post here to see if you can help. If it makes more sense to move elsewhere, please let me know. 

The problem I am having right now is that certain words are consistently being misinterpreted. Part of the reason is likely that they are not "words" in the english language -- meaning you aren't going to find them in the dictionary. Specifically, I am using the term "Liferay" which is the name of the organization that I work for. 99.9% of the time it interprets this term as **life [something else]** 

.. Is there a way to "train" the speech-to-text engine with uncommon terms or custom terms?

**Comment by ErisMik** [comment]
Yes there is! The demo in this repository uses [Picovoice Cheetah](https://github.com/Picovoice/cheetah) as the speech-to-text engine. You can create a custom model in [Picovoice Console](https://console.picovoice.ai/) with your custom vocabulary, download the model for Cheetah then pass it in as an argument to the Cheetah init/constructor. 

https://picovoice.ai/docs/cheetah/#customizations

Going to close this issue as done, but feel free to continue to comment on it or open a new issue if you need additional information.
